# Generated by Django 5.0.2 on 2024-02-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_address_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
