# Generated by Django 5.0.2 on 2024-03-01 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProfile',
            new_name='Profile',
        ),
    ]
