# Generated by Django 4.1.13 on 2024-02-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
